# Generated by Django 4.1.2 on 2023-03-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mooclist.department')),
            ],
            options={
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=25)),
                ('available', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=20)),
                ('link', models.URLField(max_length=256)),
                ('weeks', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('discipline', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mooclist.discipline')),
            ],
            options={
                'verbose_name_plural': 'Курсы',
                'ordering': ['name', 'discipline', 'platform', 'price', 'available', 'link', 'weeks', 'hours'],
            },
        ),
    ]
